services:
  - type: web
    name: airshorts-ai-video-generator
    env: node
    plan: starter
    runtime: node-22
    buildCommand: npm ci --legacy-peer-deps && npm run build
    startCommand: ./scripts/start-with-migrations.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        value: airshorts1_bot
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DID_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: DEBUG
        value: false
    healthCheckPath: /health
    autoDeploy: true
