services:
  - type: web
    name: airshorts-ai-video-generator
    env: node
    plan: starter
    buildCommand: npm ci --legacy-peer-deps
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DID_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: DEBUG
        value: false
    healthCheckPath: /health
    autoDeploy: true
